config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#welcome'

  resources :users do
    resources :rooms do
      member do
        post 'room_availability'
      end

      collection do
        post 'rooms_availability'
      end
    end
  end

  resources :rooms do
    resources :bookings, except: [:show, :edit, :update, :destroy]
  end

  resources :bookings, only: [:show, :destroy]
end

app/models/booking.rb
# == Schema Information
#
# Table name: bookings
#
#  id         :integer          not null, primary key
#  start_date :datetime
#  end_date   :datetime
#  room_id    :integer
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

# Booking model
class Booking < ApplicationRecord
  validate :dates_in_order,
           :booking_available,
           :check_start_time

  belongs_to :user
  belongs_to :room

  def room_name
    room = room_id
    Room.find(room).name
  end

  def dates_in_order
    errors.add(:start_date, 'must be before end_date.') unless start_date < end_date
  end

  def booking_available
    room = Room.find(room_id)
    errors.add(:start_date, ' and End date, are in conflict with some other booking, choose another time.') unless room.available(start_date, end_date)
  end

  def check_start_time
    errors.add(:start_date, 'must be after current time.') unless start_date > Time.current
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  # GET /bookings.json
  def index
    @room = Room.find(params[:room_id])
    @bookings = @room.bookings.all
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
    room_id = @booking.room_id
    @room = Room.find(room_id)
  end

  # GET /bookings/new
  def new
    @room = Room.find(params[:room_id])
    @booking = @room.bookings.new
  end

  # GET /bookings/1/edit
  def edit; end

  # POST /bookings
  # POST /bookings.json
  def create
    @room = Room.find(params[:room_id])
    @booking = @room.bookings.new(booking_params)

    respond_to do |format|
      if @booking.save
        format.html { redirect_to user_room_url(current_user, @room), notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to user_room_url(current_user, @room), notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @room = Room.find(@booking.room_id)
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to user_room_url(current_user, @room), notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_booking
    @booking = Booking.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<%= form_for [room, booking] do |f| %>
  <% if booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'start_date:' %>
    <%= f.datetime_select :start_date,
        start_year: DateTime.current.year, end_year: DateTime.current.year %>
  </div>

  <div class="field">
    <%= f.label 'end_date:' %>
    <%= f.datetime_select :end_date,
        start_year: DateTime.current.year, end_year: DateTime.current.year %>
  </div>

  <div class="actions">
    <%= f.submit 'Submit', class: "btn btn-success"%>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Show', @booking, class: "btn btn-success" %> |
<%= link_to 'Back', bookings_path, class: "btn btn-success" %>

app/views/bookings/index.html.erb
<h1><%= @room.name %>: Bookings</h1>

<table class="table">
  <thead>
    <tr>
      <th>Start date</th>
      <th>End date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.start_date %></td>
        <td><%= booking.end_date %></td>
        <td><%= link_to 'Show', booking_path(booking) %></td>
        <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Booking', new_room_booking_path(@room), class: "btn btn-success" %> |
<%= link_to 'back', user_room_url(current_user, @room), class: "btn btn-success" %>

app/views/bookings/new.html.erb
<h1>New Booking</h1>

<%= render 'form', room: @room, booking: @booking %>

<%= link_to 'Back', user_room_path(current_user, @room), class: "btn btn-success" %>

app/views/bookings/show.html.erb
<p>
  <strong>Start:</strong>
  <%= @booking.start_date %>
</p>

<p>
  <strong>End:</strong>
  <%= @booking.end_date %>
</p>

<p>
  <strong>Room:</strong>
  <%= @booking.room_name %>
</p>

<%= link_to 'Destroy', @booking, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-success" %> |
<%= link_to 'Back', user_room_url(current_user, @room), class: "btn btn-success" %>