config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#welcome'

  resources :users do
    resources :rooms do
      member do
        post 'room_availability'
      end

      collection do
        post 'rooms_availability'
      end
    end
  end

  resources :rooms do
    resources :bookings, except: [:show, :edit, :update, :destroy]
  end

  resources :bookings, only: [:show, :destroy]
end

app/models/room.rb
# == Schema Information
#
# Table name: rooms
#
#  id         :integer          not null, primary key
#  name       :string
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Room < ApplicationRecord
  validates :name, presence: true

  has_many :bookings
  belongs_to :user

  def owner
    id = user_id
    User.find(id).name
  end

  def available(start_date, end_date)
    bookings = self.bookings.where('(start_date < ? AND ? < end_date) or (start_date < ? AND ? < end_date) or (start_date > ? AND end_date < ?)', start_date, start_date, end_date, end_date, start_date, end_date)
    bookings.count.zero?
  end

  def self.dates_in_order(start_date, end_date)
    errors.add(:start_check, 'must be before end_date.') unless start_date < end_date
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create,
                                            :update, :destroy,
                                            :room_availability,
                                            :rooms_availability]
  before_action :set_room, only: [:show, :edit, :update, :destroy, :room_availability]
  before_action :datify, only: [:room_availability, :rooms_availability]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show; end

  # GET /rooms/new
  def new
    @user = current_user
    @room = @user.rooms.new
  end

  # GET /rooms/1/edit
  def edit
    @user = current_user
    @room = Room.find(params[:id])
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)
    @room.user_id = current_user.id

    respond_to do |format|
      if @room.save
        format.html { redirect_to user_room_url(current_user, @room), notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to user_room_url(current_user, @room), notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.bookings.destroy_all
    @room.destroy
    respond_to do |format|
      format.html { redirect_to user_rooms_url(current_user), notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def room_availability
    if @start_check > @end_check
      redirect_to user_room_url(current_user, @room), alert: "Start date must be before End date."
    else
      if @room.available(@start_check, @end_check)
        redirect_to user_room_url(current_user, @room), notice: 'Room available'
      else
        redirect_to user_room_url(current_user, @room), alert: 'Room not available'
      end
    end
  end

  def rooms_availability
    if @start_check > @end_check
      redirect_to user_rooms_url(current_user), alert: "Start date must be before End date."
    else
      rooms = current_user.rooms
      @available_rooms = []
      rooms.each do |room|
        @available_rooms << room if room.available(@start_check, @end_check)
      end
      @rooms = Room.all
      render 'index'
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_room
    @room = Room.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def room_params
    params.require(:room).permit(:name, :user_id)
  end

  def datify(start_param = params[:start_check], end_param= params[:end_check])
    @start_check = Time.utc(start_param['year'], start_param['month'], start_param['day'], start_param['hour'], start_param['minute'])
    @end_check = Time.utc(end_param['year'], end_param['month'], end_param['day'], end_param['hour'], end_param['minute'])
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_for [user, room], html: { class: "authform" } do |f| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="group-form">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit 'Submit', class: "btn btn-success" %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', user: current_user, room: @room %>

<%= link_to 'Show', user_room_path(@room), class: "btn btn-success" %> |
<%= link_to 'Back', user_rooms_path(current_user), class: "btn btn-success" %>

app/views/rooms/index.html.erb
<h2>Check available rooms:</h2>

<%= form_tag rooms_availability_user_rooms_url, method: 'post', url: {action: "rooms_availability"}, html: {class: "authform"} do %>
  <div class="field">
    <%= label_tag :start_date %>
    <%= select_datetime DateTime.current, prefix: :start_check %>
  </div>

  <div class="field">
    <%= label_tag :end_date %>
    <%= select_datetime DateTime.current, prefix: :end_check %>
  </div>

  <%= submit_tag "Check availability", class: "btn btn-success" %>
<% end %>
<br><br>
<% if @available_rooms %>
  <% if @available_rooms.empty? %>
  <h3>No rooms available :(</h3>
  <% else %>
    <div class="panel panel-default right">
      <div class="panel-heading"><h4>Available rooms:</h4></div>
      <table class="table">
        <thead>
          <tr>
            <th>#</th>
            <th>Name</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% id = 0 %>
          <% @available_rooms.each do |room| %>
          <tr>
            <% if room.user_id == current_user.id %>
              <% id = id + 1 %>
              <td><%= id %></td>
              <td><%= link_to room.name , user_room_url(current_user, room) %></td>
            <% end %>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% end %>
<% else %>
<br>
<br>
<div class="panel panel-default">
  <div class="panel-heading"><h4>Rooms:</h4></div>
  <table class="table">
    <thead>
      <tr>
        <th>#</th>
        <th>Name</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% id = 0 %>
      <% @rooms.each do |room| %>
      <tr>
        <% if room.user_id == current_user.id %>
          <% id = id + 1 %>
          <td><%= id %></td>
          <td><%= link_to room.name , user_room_url(current_user, room) %></td>
        <% end %>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>
<%= link_to 'New Room', new_user_room_path(current_user), class: "btn btn-success" %>
<br>

<% end %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', user: current_user, room: @room%>

<%= link_to 'Back', user_rooms_path, class: "btn btn-success" %>

app/views/rooms/show.html.erb
<h3>Check availability of <%= @room.name %>:</h3>

<%= form_tag room_availability_user_room_url(current_user, @room), method: 'post', url: {action: "room_availability"}, html: {class: "authform"} do %>
  <div class="field">
    <%= label_tag :start_date %>
    <%= select_datetime DateTime.current, prefix: :start_check %>
  </div>

  <div class="field">
    <%= label_tag :end_date %>
    <%= select_datetime DateTime.current, prefix: :end_check %>
  </div>

  <%= submit_tag "Check avalability", class: "btn btn-success" %>
<% end %>

<br><br>

<h3>Room: <%= @room.name %></h3>
<div class="panel panel-default">
  <div class="panel-heading"><h4>Bookings:</h4></div>
    <% if @room.bookings.empty? %>
      <p>
        No bookings for this room, try making one.
      </p>
    <% else %>
      <table class="table">
        <thead>
          <tr>
            <th>#</th>
            <th>Start date</th>
            <th>End date</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% id = 0 %>
          <% @room.bookings.all.each do |booking| %>
            <tr>
              <% id = id + 1 %>
              <td><%= id %></td>
              <td><%= booking.start_date %></td>
              <td><%= booking.end_date %></td>
              <td><%= link_to 'Show', booking_path(booking) %></td>
              <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>


<%= link_to 'New Booking', new_room_booking_path(@room), class: "btn btn-success" %>

<br><br>
<br><br>

<%= link_to 'Edit', edit_user_room_path(current_user, @room), class: "btn btn-success" %> |
<%= link_to 'Destroy', @room, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-success" %> |
<%= link_to 'Back', user_rooms_path(current_user), class: "btn btn-success" %>